# Generated by Django 4.1 on 2024-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APTEST',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('ap', models.FloatField()),
                ('annee', models.DateField()),
            ],
        ),
    ]
